### PR TITLE
Accomodates different JDK versions

### PR DESCRIPTION
**Pull request by daedric**
See discussion on #14

### CODE REVIEW

**Comment by jfirebaugh** [comment]
Thanks! I've applied a variation on the fix for the `AttachCurrentThread` inconsistency in 6654bc2438121f8bd58efce27fc0b0cdf439b05d. Do you have any more information about the `JNINativeMethod` inconsistency? How is this triggered and what are the symptoms?

**Comment by daedric** [comment]
on Android the struct is defined as following:

```
typedef struct {
    const char* name;
    const char* signature;
    void*       fnPtr;
} JNINativeMethod;
```
So it works fine, but on jdk >= 1.7 (did not try 1.6) it is defined as following:
```
typedef struct {
    char *name;
    char *signature;
    void *fnPtr;
} JNINativeMethod;
```

Which requires a const cast in jni.hpp to work. I thought that having a header accommodating differences betweek jdk could a cleaner :)

**Comment by daedric** [comment]
BTW those are the errors:

```
In file included from /Users/daedric/work/perso/jni.hpp/examples/hello.cpp:1:
In file included from /Users/daedric/work/perso/jni.hpp/include/jni/jni.hpp:6:
In file included from /Users/daedric/work/perso/jni.hpp/include/jni/functions.hpp:5:
/Users/daedric/work/perso/jni.hpp/include/jni/wrapping.hpp:141:22: error: cannot initialize a member subobject of type 'char *' with an lvalue of type 'const char *'
            return { method.name, method.signature, reinterpret_cast<void*>(method.fnPtr) };
                     ^~~~~~~~~~~
/Users/daedric/work/perso/jni.hpp/include/jni/wrapping.hpp:24:56: note: in instantiation of member function 'jni::Wrapper<jni::JNINativeMethod<void
      (JNIEnv_ *, jni::jobject *, jni::jarray<jni::jobject> *)> >::Unwrap' requested here
        return Wrapper<typename std::decay<W>::type>().Unwrap(std::forward<W>(w));
                                                       ^
/Users/daedric/work/perso/jni.hpp/examples/hello.cpp:35:10: note: in instantiation of function template specialization 'jni::RegisterNatives<jni::JNINativeMethod<void
      (JNIEnv_ *, jni::jobject *, jni::jarray<jni::jobject> *)> >' requested here
    jni::RegisterNatives(env, jni::FindClass(env, "LowLevelGreeter"),
         ^
In file included from /Users/daedric/work/perso/jni.hpp/examples/hello.cpp:1:
In file included from /Users/daedric/work/perso/jni.hpp/include/jni/jni.hpp:6:
In file included from /Users/daedric/work/perso/jni.hpp/include/jni/functions.hpp:5:
/Users/daedric/work/perso/jni.hpp/include/jni/wrapping.hpp:141:35: error: cannot initialize a member subobject of type 'char *' with an lvalue of type 'const char *'
            return { method.name, method.signature, reinterpret_cast<void*>(method.fnPtr) };
                                  ^~~~~~~~~~~~~~~~
2 errors generated.
make[2]: *** [CMakeFiles/hello.dir/examples/hello.cpp.o] Error 1
make[1]: *** [CMakeFiles/hello.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by jfirebaugh** [comment]
Thanks! In that case we can cast unconditionally, since `char*` ⇢ `const char*` will convert implicitly. Fixed in 575890982bd58219a6ad6a61920205b9c52f9d48.

**Pull request closed without merging**
